### ISSUE TITLE
Landing page simples

### ISSUE THREAD

**Issue by Jefvidal** [Jefvidal/Free-codes#1]

**Comment by Jefvidal** [comment]
> 
```html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
  
    <meta charset="UTF-8">
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <meta name="description" content="Landing page simples">
    
    <link rel="stylesheet" type="text/css" href="style.css">
   
    <title>Landing page simples - HTML e css</title>
    
</head>
<body class="corpo">
<header class="cabecalho">
  
  <img class="cabecalho-imagem" src="Minhalogo.png" alt="Logo de Jeferson">
  
  <nav class="cabecalho-menu">
    
    <a class="cabecalho-menu-item">Contatos</a>
    <a class="cabecalho-menu-item"> Github </a>
    
  </nav>
</header>

<main class="conteudos">
  <section class="conteudo-principal">
    <div class="conteudo-principal-escrito">
      
      <h1 class="conteudo-principal-escrito-titulo">Jeferson Dev</h1>
      <h2 class="conteudo-principal-escrito-subtitulo">Este é meu site de Portifolio e projetos pessoais</h2>
      
        <button class="conteudo-principal-escrito-botao">Acessar projetos</button>
        
          <img class="conteudo-principal-imagem" src="Dev.png"  alt="imagem dev">
      
     </div>
   </section>
   
   
 <section class="conteudo-secundario">
    
  <h3 class="conteudo-secundario-titulo">Projetos Futuros</h2>
    
      <p class="conteudo-secundario-paragrafo">Desenvolvimento de aplicativos com react native</p>
      <p class="conteudo-secundario-paragrafo">Desenvolvimento de uma biblioteca para <strong>DEVS</strong></p>
      <p class="conteudo-secundario-paragrafo">Desenvolvimento de uma rede social privada com foco em privacidade e anonimato</p>
  
  </section>
</main>

<footer class="rodape">
  <img class="rodape-imagem" src="Footerlogo.png" alt="logo-rodape">
</footer>

</body>
</html>
```

**Comment by Jefvidal** [comment]
```css
@import url('https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Sarala&display=swap');

* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  text-decoration: none;
}

body {
  fonte-size:100%;
  background: linear-gradient(to bottom, #ffffff, #507E70);
}

.cabecalho {
  display: flex;
  flex-flow: row;
  align-items: center;
  justify-content: space-around;
  padding: 10px;
}

.cabecalho-imagem {
  width: 80px;
}

.cabecalho-menu {
  display: flex;
  gap: 30px;
}

.cabecalho-menu-item {
  font-family: Sarala;
  color: #000000;
  font-weight: 400px;
  font-size: 18px;
}

.conteudos {
  margin-bottom: 48px;
  border-top: 0.4px solid #000000;
}

.conteudo-principal {
  display: flex;
  flex-direction: row;
  align-items: center;
  justify-content: space-around;
  padding: 10px;
}

.conteudo-principal-escrito {
  display: flex;
  flex-direction: column;
  gap: 32px;
}
.conteudo-principal-escrito-titulo {
  font-family: Bebas;
  font-weight: 400;
  font-size: 64px;
  color: #000000;
  padding: 10px;
}

.conteudo-principal-escrito-subtitulo {
  font-family: Sarala;
  font-weight: 400;
  font-size: 24px;
}

.conteudo-principal-escrito-botao {
  background-color: #E4FFF3;
  width: 180px;
  height: 40px;
  border: none;
  box-shadow: 4px 5px 4px rgba(0, 0, 0, 0.25);
  border-radius: 20px;
  font-family: Sarala;
  font-size: 20px;
  color: #000000;
}

.conteudo-principal-escrito-botao:hover {
  background-color: transparent;
}

.conteudo-principal-imagem {
  width: 430px;
}

.conteudo-secundario {
  display: flex;
  flex-direction: column;
  align-items: center;
  font-family: Sarala;
  gap: 24px;
  margin-top: 48px;
}

.conteudo-secundario-titulo {
  border-top: 0.4x solid #000000;
  padding-top: 48px;
  font-family: 'righteus', cursive;
  font-weight: 400px;
  font-size: 24px;
  color: #ffffff;
  margin-bottom: 16px;
}

.conteudo-secundario-paragrafo {
  font-family: Sarala;
  font-size: 16px;
  color: #fffffd;
  
}

.rodape {
  padding: 32px;
  border-top: 0.4px solid #000000;
  
}

.rodape-imagem {
  width: 120px;
  display: block;
  margin: 0 auto;
}
```
